#!/usr/bin/env python3
"""Add 120 more questions to questions.js (appended to existing data)."""
import json

# Read existing data
with open("/Users/maximeleboeuf/Cadet AF/PSY0_Training/data/questions.js", 'r', encoding='utf-8') as f:
    content = f.read()

# Extract existing qcmData
import re
qcm_match = re.search(r'const qcmData = (\[.*?\]);\s*\n\nconst flashcardData', content, re.DOTALL)
fc_match = re.search(r'const flashcardData = (\[.*?\]);', content, re.DOTALL)
existing_q = json.loads(qcm_match.group(1))
existing_fc = json.loads(fc_match.group(1))
print(f"Existing: {len(existing_q)} questions, {len(existing_fc)} flashcards")

new_q = [
    # --- HISTOIRE APPROFONDIE ---
    {"id":201,"question":"Premier dirigeable motorisé (1852) ?","options":[{"id":"a","text":"Zeppelin"},{"id":"b","text":"Henri Giffard"},{"id":"c","text":"Santos-Dumont"},{"id":"d","text":"Montgolfier"}],"answer":"b","category":"Histoire","explanation":"Henri Giffard en 1852, propulsé par une machine à vapeur."},
    {"id":202,"question":"Premier ballon à gaz (hydrogène) ?","options":[{"id":"a","text":"Montgolfier"},{"id":"b","text":"Pilâtre de Rozier"},{"id":"c","text":"Jacques Charles"},{"id":"d","text":"Blanchard"}],"answer":"c","category":"Histoire","explanation":"Jacques Charles, 1783, aux Tuileries à Paris."},
    {"id":203,"question":"Jorge Chávez est connu pour ?","options":[{"id":"a","text":"Traversée de la Manche"},{"id":"b","text":"Traversée des Alpes"},{"id":"c","text":"Traversée de l'Atlantique"},{"id":"d","text":"Premier looping"}],"answer":"b","category":"Histoire","explanation":"Première traversée aérienne des Alpes en 1910. Il meurt à l'atterrissage."},
    {"id":204,"question":"Richthofen était surnommé ?","options":[{"id":"a","text":"L'As des As"},{"id":"b","text":"Le Baron Rouge"},{"id":"c","text":"L'Aigle Noir"},{"id":"d","text":"Le Faucon"}],"answer":"b","category":"Histoire","explanation":"Manfred von Richthofen, 80 victoires, pilote allemand de la WWI."},
    {"id":205,"question":"Guynemer avait combien de victoires ?","options":[{"id":"a","text":"30"},{"id":"b","text":"45"},{"id":"c","text":"54"},{"id":"d","text":"75"}],"answer":"c","category":"Histoire","explanation":"Guynemer : 54 victoires. Fonck : 75 victoires (top as allié)."},
    {"id":206,"question":"Citation de Guillaumet après son crash dans les Andes ?","options":[{"id":"a","text":"L'aviation vaincra"},{"id":"b","text":"Ce que j'ai fait, aucune bête ne l'aurait fait"},{"id":"c","text":"Je reviendrai"},{"id":"d","text":"Le ciel est mon domaine"}],"answer":"b","category":"Histoire","explanation":"1929, Guillaumet survit 5 jours dans la neige après un crash dans les Andes."},
    {"id":207,"question":"Amelia Earhart disparue au-dessus de ?","options":[{"id":"a","text":"L'Atlantique"},{"id":"b","text":"Les Andes"},{"id":"c","text":"Le Pacifique"},{"id":"d","text":"L'Arctique"}],"answer":"c","category":"Histoire","explanation":"Disparue en 1937 au-dessus du Pacifique."},
    {"id":208,"question":"Avions mythiques de la WWI : le Spitfire est ?","options":[{"id":"a","text":"Un bombardier allemand"},{"id":"b","text":"Un chasseur britannique"},{"id":"c","text":"Un avion de reconnaissance français"},{"id":"d","text":"Un chasseur américain"}],"answer":"b","category":"Histoire","explanation":"Spitfire 🇬🇧 (chasseur, ailes elliptiques). P-51 Mustang 🇺🇸. Bf 109 🇩🇪."},
    {"id":209,"question":"Moteur du P-51 Mustang ?","options":[{"id":"a","text":"Wright Cyclone"},{"id":"b","text":"Rolls-Royce Merlin"},{"id":"c","text":"BMW 801"},{"id":"d","text":"Pratt & Whitney"}],"answer":"b","category":"Histoire","explanation":"Le P-51 Mustang utilisait le moteur Rolls-Royce Merlin pour l'escorte longue portée."},
    {"id":210,"question":"Premier avion civil fly-by-wire ?","options":[{"id":"a","text":"B777"},{"id":"b","text":"Concorde"},{"id":"c","text":"A320"},{"id":"d","text":"A300"}],"answer":"c","category":"Histoire","explanation":"L'A320 (1988) est le premier avion civil Airbus avec commandes de vol électriques (mini-manche latéral)."},
    {"id":211,"question":"Premier vol A300 ?","options":[{"id":"a","text":"1970"},{"id":"b","text":"1972"},{"id":"c","text":"1976"},{"id":"d","text":"1980"}],"answer":"b","category":"Histoire","explanation":"A300 : premier vol en 1972, premier gros-porteur biréacteur au monde."},
    {"id":212,"question":"Record vitesse SR-71 Blackbird ?","options":[{"id":"a","text":"Mach 2.0"},{"id":"b","text":"Mach 2.5"},{"id":"c","text":"Mach 3.3"},{"id":"d","text":"Mach 4.0"}],"answer":"c","category":"Histoire","explanation":"SR-71 Blackbird : Mach 3.3 (3 540 km/h), altitude 25 929 m."},
    {"id":213,"question":"Rafale en service (Marine) depuis ?","options":[{"id":"a","text":"1996"},{"id":"b","text":"2001"},{"id":"c","text":"2006"},{"id":"d","text":"2010"}],"answer":"b","category":"Histoire","explanation":"Rafale : Marine 2001, Armée de l'Air 2006. Mach 1.8, Dassault Aviation."},
    {"id":214,"question":"Moteur du Rafale ?","options":[{"id":"a","text":"Olympus 593"},{"id":"b","text":"M88"},{"id":"c","text":"EJ200"},{"id":"d","text":"F100"}],"answer":"b","category":"Histoire","explanation":"Snecma/Safran M88. 2 moteurs."},
    {"id":215,"question":"Premiers A320neo chez Transavia France ?","options":[{"id":"a","text":"2020"},{"id":"b","text":"2022"},{"id":"c","text":"2023"},{"id":"d","text":"2025"}],"answer":"c","category":"Histoire","explanation":"Premiers A320neo livrés à Transavia France en 2023, avec moteurs LEAP."},

    # --- AIR FRANCE APPROFONDI ---
    {"id":216,"question":"Nationalisation d'Air France ?","options":[{"id":"a","text":"1933"},{"id":"b","text":"1940"},{"id":"c","text":"1945"},{"id":"d","text":"1950"}],"answer":"c","category":"Air France & Flotte","explanation":"Nationalisation en 1945 sous De Gaulle."},
    {"id":217,"question":"Air France s'installe à Orly en ?","options":[{"id":"a","text":"1948"},{"id":"b","text":"1952"},{"id":"c","text":"1960"},{"id":"d","text":"1970"}],"answer":"b","category":"Air France & Flotte","explanation":"Terminal Sud d'Orly, 1952."},
    {"id":218,"question":"Lancement de Flying Blue ?","options":[{"id":"a","text":"2000"},{"id":"b","text":"2003"},{"id":"c","text":"2005"},{"id":"d","text":"2008"}],"answer":"c","category":"Air France & Flotte","explanation":"Flying Blue lancé en 2005, année de la privatisation d'AF."},
    {"id":219,"question":"Nombre de membres Flying Blue ?","options":[{"id":"a","text":"5 millions"},{"id":"b","text":"10 millions"},{"id":"c","text":"20 millions"},{"id":"d","text":"50 millions"}],"answer":"c","category":"Air France & Flotte","explanation":"+20 millions de membres Flying Blue."},
    {"id":220,"question":"Club des Actionnaires AF-KLM : dès combien d'actions ?","options":[{"id":"a","text":"10"},{"id":"b","text":"25"},{"id":"c","text":"50"},{"id":"d","text":"100"}],"answer":"c","category":"Air France & Flotte","explanation":"Dès 50 actions AF-KLM."},
    {"id":221,"question":"Chiffre d'affaires groupe AF-KLM ?","options":[{"id":"a","text":"~10 Md€"},{"id":"b","text":"~20 Md€"},{"id":"c","text":"~30 Md€"},{"id":"d","text":"~50 Md€"}],"answer":"c","category":"Air France & Flotte","explanation":"~30 Md€ de CA. Objectif marge exploitation : 7-8%."},
    {"id":222,"question":"Passagers/an groupe AF-KLM ?","options":[{"id":"a","text":"~50 millions"},{"id":"b","text":"~80 millions"},{"id":"c","text":"~100 millions"},{"id":"d","text":"~150 millions"}],"answer":"c","category":"Air France & Flotte","explanation":"~100 millions pax/an pour le groupe, ~50 millions pour AF seul."},
    {"id":223,"question":"Employés groupe AF-KLM ?","options":[{"id":"a","text":"~40 000"},{"id":"b","text":"~60 000"},{"id":"c","text":"~80 000"},{"id":"d","text":"~120 000"}],"answer":"c","category":"Air France & Flotte","explanation":"~80 000 employés groupe. ~43 000 pour AF seul."},
    {"id":224,"question":"Max Hymans, modernisation avec quel avion ?","options":[{"id":"a","text":"DC-3"},{"id":"b","text":"Concorde"},{"id":"c","text":"Caravelle"},{"id":"d","text":"A300"}],"answer":"c","category":"Air France & Flotte","explanation":"Max Hymans (1948-1961) : modernisation avec Caravelle, B707, Super Constellation."},
    {"id":225,"question":"Pierre-Henri Gourgeon, période ?","options":[{"id":"a","text":"2005-2008"},{"id":"b","text":"2009-2011"},{"id":"c","text":"2011-2016"},{"id":"d","text":"2016-2018"}],"answer":"b","category":"Air France & Flotte","explanation":"Gourgeon : 2009-2011, période post-AF447."},
    {"id":226,"question":"Plan 'Transform 2015' sous quel dirigeant ?","options":[{"id":"a","text":"Smith"},{"id":"b","text":"Janaillac"},{"id":"c","text":"De Juniac"},{"id":"d","text":"Spinetta"}],"answer":"c","category":"Air France & Flotte","explanation":"Alexandre de Juniac (2011-2016) : plan Transform 2015, redressement financier."},

    # --- FLOTTE TECHNIQUE ---
    {"id":227,"question":"MTOW du B777-300ER ?","options":[{"id":"a","text":"280 t"},{"id":"b","text":"310 t"},{"id":"c","text":"351 t"},{"id":"d","text":"400 t"}],"answer":"c","category":"Air France & Flotte","explanation":"351 tonnes. Le plus lourd de la flotte AF."},
    {"id":228,"question":"Passagers B777-300ER chez AF ?","options":[{"id":"a","text":"~324"},{"id":"b","text":"~400"},{"id":"c","text":"~468"},{"id":"d","text":"~550"}],"answer":"c","category":"Air France & Flotte","explanation":"~468 passagers en 3 classes."},
    {"id":229,"question":"Envergure de l'A350-900 ?","options":[{"id":"a","text":"35,1 m"},{"id":"b","text":"60,3 m"},{"id":"c","text":"64,75 m"},{"id":"d","text":"79,75 m"}],"answer":"c","category":"Air France & Flotte","explanation":"64,75 m. Longueur : 66,80 m."},
    {"id":230,"question":"Composition fuselage A350 ?","options":[{"id":"a","text":"100% aluminium"},{"id":"b","text":"53% carbone"},{"id":"c","text":"30% titane"},{"id":"d","text":"80% acier"}],"answer":"b","category":"Air France & Flotte","explanation":"53% carbone, -25% consommation vs A340."},
    {"id":231,"question":"Nombre de Boeing 777F (cargo) chez AF ?","options":[{"id":"a","text":"0"},{"id":"b","text":"2"},{"id":"c","text":"5"},{"id":"d","text":"10"}],"answer":"b","category":"Air France & Flotte","explanation":"2 Boeing 777F, version cargo du B777."},
    {"id":232,"question":"Plafond de l'A320 ?","options":[{"id":"a","text":"35 000 ft"},{"id":"b","text":"37 000 ft"},{"id":"c","text":"39 100 ft"},{"id":"d","text":"43 000 ft"}],"answer":"c","category":"Air France & Flotte","explanation":"FL410 max pour l'A320 (39 100 ft)."},
    {"id":233,"question":"Consommation horaire A320 (total 2 moteurs) ?","options":[{"id":"a","text":"~2 700 L/h"},{"id":"b","text":"~3 500 L/h"},{"id":"c","text":"~5 400 L/h"},{"id":"d","text":"~8 000 L/h"}],"answer":"c","category":"Air France & Flotte","explanation":"~2 700 kg/h par moteur, soit ~5 400 L/h total."},
    {"id":234,"question":"Longueur de l'A321 ?","options":[{"id":"a","text":"37,57 m"},{"id":"b","text":"44,51 m"},{"id":"c","text":"50 m"},{"id":"d","text":"33,84 m"}],"answer":"b","category":"Air France & Flotte","explanation":"A321 = 44,51 m. C'est le plus long de la famille A320."},
    {"id":235,"question":"Autonomie de l'A220-300 ?","options":[{"id":"a","text":"3 500 km"},{"id":"b","text":"5 000 km"},{"id":"c","text":"6 300 km"},{"id":"d","text":"8 000 km"}],"answer":"c","category":"Air France & Flotte","explanation":"6 300 km. -20% CO₂, -34% bruit vs ancienne génération."},
    {"id":236,"question":"Réduction CO₂ de l'A220 vs ancienne génération ?","options":[{"id":"a","text":"-10%"},{"id":"b","text":"-20%"},{"id":"c","text":"-30%"},{"id":"d","text":"-50%"}],"answer":"b","category":"Air France & Flotte","explanation":"-20% CO₂ et -34% bruit."},
    {"id":237,"question":"Moteur A380 ?","options":[{"id":"a","text":"GE90"},{"id":"b","text":"Trent XWB"},{"id":"c","text":"GP7200 ou Trent 900"},{"id":"d","text":"CFM56"}],"answer":"c","category":"Air France & Flotte","explanation":"4× GP7200 (Engine Alliance: GE+P&W) ou Trent 900 (RR)."},
    {"id":238,"question":"Nombre max de passagers A380 (config max) ?","options":[{"id":"a","text":"516"},{"id":"b","text":"700"},{"id":"c","text":"853"},{"id":"d","text":"1000"}],"answer":"c","category":"Air France & Flotte","explanation":"853 pax max (classe unique). AF : 516 pax."},
    {"id":239,"question":"Moteur du Concorde ?","options":[{"id":"a","text":"GE90"},{"id":"b","text":"Olympus 593"},{"id":"c","text":"Trent 700"},{"id":"d","text":"CFM56"}],"answer":"b","category":"Air France & Flotte","explanation":"4× Olympus 593 (Rolls-Royce / Snecma)."},

    # --- TECHNIQUE APPROFONDI ---
    {"id":240,"question":"La portance dépend de (entre autres) ?","options":[{"id":"a","text":"V² et surface alaire"},{"id":"b","text":"Température seule"},{"id":"c","text":"Nombre de moteurs"},{"id":"d","text":"Couleur de l'avion"}],"answer":"a","category":"Technique de Vol","explanation":"Portance dépend de : V², surface alaire, Cz (coefficient de portance), ρ (masse volumique de l'air)."},
    {"id":241,"question":"g = ?","options":[{"id":"a","text":"8,81 m/s²"},{"id":"b","text":"9,81 m/s²"},{"id":"c","text":"10,81 m/s²"},{"id":"d","text":"11,81 m/s²"}],"answer":"b","category":"Technique de Vol","explanation":"g = 9,81 m/s². Poids = masse × g."},
    {"id":242,"question":"Traînée induite est due à ?","options":[{"id":"a","text":"Le frottement"},{"id":"b","text":"La forme de l'avion"},{"id":"c","text":"La portance"},{"id":"d","text":"Le poids"}],"answer":"c","category":"Technique de Vol","explanation":"La traînée induite est due à la portance. Traînée totale = forme + induite + frottement."},
    {"id":243,"question":"Pour virer à gauche, l'aileron gauche ?","options":[{"id":"a","text":"Se baisse"},{"id":"b","text":"Se lève"},{"id":"c","text":"Ne bouge pas"},{"id":"d","text":"Se rétracte"}],"answer":"b","category":"Technique de Vol","explanation":"Aileron gauche se lève (portance↓) + aileron droit se baisse (portance↑) → roulis gauche."},
    {"id":244,"question":"L'incidence est l'angle entre ?","options":[{"id":"a","text":"L'avion et l'horizontale"},{"id":"b","text":"L'axe longitudinal et le vent relatif"},{"id":"c","text":"La trajectoire et le nord"},{"id":"d","text":"Les ailes et le sol"}],"answer":"b","category":"Technique de Vol","explanation":"Incidence α = angle entre l'axe longitudinal et le vent relatif (= la trajectoire)."},
    {"id":245,"question":"En montée, quelle condition ?","options":[{"id":"a","text":"Portance > Poids"},{"id":"b","text":"Poussée > Traînée"},{"id":"c","text":"Traînée > Poussée"},{"id":"d","text":"Poids > Portance"}],"answer":"b","category":"Technique de Vol","explanation":"Montée : Poussée > Traînée. Descente : Traînée > Poussée."},
    {"id":246,"question":"Centrage arrière = ?","options":[{"id":"a","text":"Plus stable, plus conso"},{"id":"b","text":"Moins stable, moins conso"},{"id":"c","text":"Plus stable, moins conso"},{"id":"d","text":"Aucun effet"}],"answer":"b","category":"Technique de Vol","explanation":"Centrage arrière = moins stable, plus manœuvrant, consomme moins. Centrage avant = plus stable, plus conso."},
    {"id":247,"question":"ECAM est un système ?","options":[{"id":"a","text":"Boeing"},{"id":"b","text":"Airbus"},{"id":"c","text":"Embraer"},{"id":"d","text":"Dassault"}],"answer":"b","category":"Technique de Vol","explanation":"ECAM = Airbus. EICAS = Boeing. Les deux affichent pannes et procédures."},
    {"id":248,"question":"ELT signifie ?","options":[{"id":"a","text":"Electronic Landing Tool"},{"id":"b","text":"Emergency Locator Transmitter"},{"id":"c","text":"Engine Load Tracker"},{"id":"d","text":"External Light Test"}],"answer":"b","category":"Technique de Vol","explanation":"ELT = balise de détresse activée automatiquement en cas de crash."},
    {"id":249,"question":"FDR enregistre au minimum ?","options":[{"id":"a","text":"2h"},{"id":"b","text":"10h"},{"id":"c","text":"25h"},{"id":"d","text":"100h"}],"answer":"c","category":"Technique de Vol","explanation":"FDR = min 25h, ~1000 paramètres. CVR = min 2h (voix cockpit)."},
    {"id":250,"question":"VMO de l'A320 ?","options":[{"id":"a","text":"250 kt"},{"id":"b","text":"300 kt"},{"id":"c","text":"350 kt"},{"id":"d","text":"400 kt"}],"answer":"c","category":"Technique de Vol","explanation":"VMO = 350 kt IAS. MMO = Mach 0.82."},
    {"id":251,"question":"MMO de l'A320 ?","options":[{"id":"a","text":"Mach 0.78"},{"id":"b","text":"Mach 0.80"},{"id":"c","text":"Mach 0.82"},{"id":"d","text":"Mach 0.85"}],"answer":"c","category":"Technique de Vol","explanation":"MMO = Mach 0.82. Vitesse de croisière = Mach 0.78."},
    {"id":252,"question":"VLOF signifie ?","options":[{"id":"a","text":"Vitesse de décision"},{"id":"b","text":"Vitesse de décollage effectif"},{"id":"c","text":"Vitesse de rotation"},{"id":"d","text":"Vitesse de sécurité"}],"answer":"b","category":"Technique de Vol","explanation":"VLOF = l'avion quitte le sol. Juste après VR."},
    {"id":253,"question":"V2 doit être atteinte au plus tard à ?","options":[{"id":"a","text":"10 ft"},{"id":"b","text":"35 ft"},{"id":"c","text":"100 ft"},{"id":"d","text":"200 ft"}],"answer":"b","category":"Technique de Vol","explanation":"V2 = vitesse min pour monter avec 1 moteur en panne, atteinte au plus tard à 35 ft."},
    {"id":254,"question":"Va est la vitesse de ?","options":[{"id":"a","text":"Approche"},{"id":"b","text":"Manœuvre"},{"id":"c","text":"Décrochage"},{"id":"d","text":"Ne jamais dépasser"}],"answer":"b","category":"Technique de Vol","explanation":"Va = vitesse de manœuvre (braquages max sans dommage structural). Vne = ne jamais dépasser."},
    {"id":255,"question":"GS (Ground Speed) = ?","options":[{"id":"a","text":"IAS + vent"},{"id":"b","text":"TAS ± composante de vent"},{"id":"c","text":"Mach × altitude"},{"id":"d","text":"CAS corrigée"}],"answer":"b","category":"Technique de Vol","explanation":"GS = TAS ± vent. C'est celle qui détermine le temps de vol réel."},
    {"id":256,"question":"Vitesse du son à 15°C au sol ?","options":[{"id":"a","text":"~295 m/s"},{"id":"b","text":"~340 m/s"},{"id":"c","text":"~400 m/s"},{"id":"d","text":"~500 m/s"}],"answer":"b","category":"Technique de Vol","explanation":"~340 m/s (1 224 km/h) à 15°C. ~295 m/s à FL350 (-56.5°C)."},
    {"id":257,"question":"Statoréacteur (ramjet) : pas de ?","options":[{"id":"a","text":"Carburant"},{"id":"b","text":"Pièces mobiles"},{"id":"c","text":"Poussée"},{"id":"d","text":"Chaleur"}],"answer":"b","category":"Technique de Vol","explanation":"Le statoréacteur n'a pas de pièces mobiles, comprimé par la vitesse (> Mach 2)."},
    {"id":258,"question":"Taux de dilution du Trent XWB ?","options":[{"id":"a","text":"~3"},{"id":"b","text":"~6"},{"id":"c","text":"~9.6"},{"id":"d","text":"~15"}],"answer":"c","category":"Technique de Vol","explanation":"Trent XWB : ~9.6. LEAP : ~11. CFM56 : ~6."},

    # --- NAVIGATION APPROFONDI ---
    {"id":259,"question":"Le VOR émet des ?","options":[{"id":"a","text":"Signaux GPS"},{"id":"b","text":"Radiales"},{"id":"c","text":"Ondes radar"},{"id":"d","text":"Impulsions laser"}],"answer":"b","category":"Navigation & Météo","explanation":"360 radiales partant de la balise, chacune nommée par son cap magnétique."},
    {"id":260,"question":"CDI signifie ?","options":[{"id":"a","text":"Central Data Interface"},{"id":"b","text":"Course Deviation Indicator"},{"id":"c","text":"Climb/Descend Indicator"},{"id":"d","text":"Compass Direction Input"}],"answer":"b","category":"Navigation & Météo","explanation":"CDI = aiguille de déviation de route, utilisée avec le VOR."},
    {"id":261,"question":"Cat I ILS : DH minimum ?","options":[{"id":"a","text":"50 ft"},{"id":"b","text":"100 ft"},{"id":"c","text":"200 ft"},{"id":"d","text":"500 ft"}],"answer":"c","category":"Navigation & Météo","explanation":"Cat I : DH ≥ 200 ft, RVR ≥ 550 m."},
    {"id":262,"question":"Cat II ILS : RVR minimum ?","options":[{"id":"a","text":"75 m"},{"id":"b","text":"200 m"},{"id":"c","text":"300 m"},{"id":"d","text":"550 m"}],"answer":"c","category":"Navigation & Météo","explanation":"Cat II : DH ≥ 100 ft, RVR ≥ 300 m."},
    {"id":263,"question":"SBAS en Europe s'appelle ?","options":[{"id":"a","text":"WAAS"},{"id":"b","text":"EGNOS"},{"id":"c","text":"MSAS"},{"id":"d","text":"GAGAN"}],"answer":"b","category":"Navigation & Météo","explanation":"EGNOS = European Geostationary Navigation Overlay Service."},
    {"id":264,"question":"CPDLC signifie ?","options":[{"id":"a","text":"Communication par datalink"},{"id":"b","text":"Contrôle de pression cabine"},{"id":"c","text":"Calcul de performance"},{"id":"d","text":"Centre de prévision"}],"answer":"a","category":"Navigation & Météo","explanation":"Controller-Pilot Data Link Communication. Utilisé en transatlantique."},
    {"id":265,"question":"RVSM = espacement de ?","options":[{"id":"a","text":"500 ft"},{"id":"b","text":"1 000 ft"},{"id":"c","text":"2 000 ft"},{"id":"d","text":"5 000 ft"}],"answer":"b","category":"Navigation & Météo","explanation":"RVSM : 1 000 ft au-dessus du FL290 (au lieu de 2 000 ft autrefois)."},
    {"id":266,"question":"Altitude de transition en France ?","options":[{"id":"a","text":"3 000 ft"},{"id":"b","text":"5 000 ft"},{"id":"c","text":"10 000 ft"},{"id":"d","text":"18 000 ft"}],"answer":"b","category":"Navigation & Météo","explanation":"Généralement 5 000 ft en France (peut varier)."},
    {"id":267,"question":"FIR = ?","options":[{"id":"a","text":"Flight Information Region"},{"id":"b","text":"Final Instrument Route"},{"id":"c","text":"Fuel Injection Rate"},{"id":"d","text":"Fire Investigation Report"}],"answer":"a","category":"Navigation & Météo","explanation":"FIR = espace inférieur (sous FL195). UIR = espace supérieur."},
    {"id":268,"question":"Aéroport le plus fréquenté au monde (passagers) ?","options":[{"id":"a","text":"Dubai"},{"id":"b","text":"Heathrow"},{"id":"c","text":"Atlanta"},{"id":"d","text":"CDG"}],"answer":"c","category":"Navigation & Météo","explanation":"Atlanta (ATL) : ~93 millions de passagers/an."},
    {"id":269,"question":"Nombre de pistes à Schiphol (Amsterdam) ?","options":[{"id":"a","text":"3"},{"id":"b","text":"4"},{"id":"c","text":"5"},{"id":"d","text":"6"}],"answer":"d","category":"Navigation & Météo","explanation":"6 pistes. Hub KLM."},
    {"id":270,"question":"Codes OACI : LF = ?","options":[{"id":"a","text":"Allemagne"},{"id":"b","text":"Royaume-Uni"},{"id":"c","text":"France"},{"id":"d","text":"Espagne"}],"answer":"c","category":"Navigation & Météo","explanation":"LF = France. EG = UK. ED = Allemagne."},

    # --- MÉTÉO APPROFONDI ---
    {"id":271,"question":"BKN en couverture nuageuse ?","options":[{"id":"a","text":"1-2/8"},{"id":"b","text":"3-4/8"},{"id":"c","text":"5-7/8"},{"id":"d","text":"8/8"}],"answer":"c","category":"Navigation & Météo","explanation":"FEW=1-2/8, SCT=3-4/8, BKN=5-7/8, OVC=8/8."},
    {"id":272,"question":"TAF est une ?","options":[{"id":"a","text":"Observation"},{"id":"b","text":"Prévision aérodrome"},{"id":"c","text":"Carte météo"},{"id":"d","text":"Alerte orage"}],"answer":"b","category":"Navigation & Météo","explanation":"TAF = prévision aérodrome (même format que METAR + BECMG, TEMPO, PROB30/40, FM)."},
    {"id":273,"question":"Heure Z = ?","options":[{"id":"a","text":"Heure locale"},{"id":"b","text":"Heure UTC"},{"id":"c","text":"Heure de Paris"},{"id":"d","text":"Heure de New York"}],"answer":"b","category":"Navigation & Météo","explanation":"Z = Zulu = UTC (temps universel coordonné)."},
    {"id":274,"question":"Cirrus sont constitués de ?","options":[{"id":"a","text":"Gouttelettes d'eau"},{"id":"b","text":"Cristaux de glace"},{"id":"c","text":"Poussière"},{"id":"d","text":"Vapeur d'eau"}],"answer":"b","category":"Navigation & Météo","explanation":"Cirrus = nuages hauts (6-12 km), filaments de cristaux de glace, beau temps."},
    {"id":275,"question":"Le Nimbostratus produit ?","options":[{"id":"a","text":"Des orages"},{"id":"b","text":"De la pluie continue"},{"id":"c","text":"De la grêle"},{"id":"d","text":"Du beau temps"}],"answer":"b","category":"Navigation & Météo","explanation":"Nimbostratus = nuage bas (0-3 km), pluie continue."},
    {"id":276,"question":"Inversion de température = ?","options":[{"id":"a","text":"T° diminue normalement"},{"id":"b","text":"T° augmente avec l'altitude"},{"id":"c","text":"T° reste constante"},{"id":"d","text":"T° chute brutalement"}],"answer":"b","category":"Navigation & Météo","explanation":"Anormal : la T° augmente avec l'altitude. Bloque la convection, brouillard/smog."},
    {"id":277,"question":"Couche d'ozone dans ?","options":[{"id":"a","text":"Troposphère"},{"id":"b","text":"Stratosphère"},{"id":"c","text":"Mésosphère"},{"id":"d","text":"Exosphère"}],"answer":"b","category":"Navigation & Météo","explanation":"Couche d'ozone dans la stratosphère (~20-40 km)."},
    {"id":278,"question":"QFE affiche ?","options":[{"id":"a","text":"L'altitude"},{"id":"b","text":"Le niveau de vol"},{"id":"c","text":"La hauteur au-dessus du terrain"},{"id":"d","text":"La température"}],"answer":"c","category":"Navigation & Météo","explanation":"QFE = hauteur au-dessus du terrain. Peu utilisé en France."},
    {"id":279,"question":"Si QNH < 1013, l'avion vole ?","options":[{"id":"a","text":"Plus haut qu'affiché"},{"id":"b","text":"Plus bas qu'affiché"},{"id":"c","text":"À la bonne altitude"},{"id":"d","text":"Plus vite"}],"answer":"b","category":"Navigation & Météo","explanation":"QNH < 1013 → on vole plus bas qu'affiché → danger relief ! « High to low, look out below! »"},
    {"id":280,"question":"Température ISA à 20 000 ft ?","options":[{"id":"a","text":"-5°C"},{"id":"b","text":"-15°C"},{"id":"c","text":"-25°C"},{"id":"d","text":"-35°C"}],"answer":"c","category":"Navigation & Météo","explanation":"15 - (20 × 2) = -25°C."},

    # --- SÉCURITÉ & RÉGLEMENTATION ---
    {"id":281,"question":"Vol Iran Air 655 abattu par ?","options":[{"id":"a","text":"Un avion de chasse"},{"id":"b","text":"USS Vincennes"},{"id":"c","text":"Un missile sol-air"},{"id":"d","text":"Une erreur de pilotage"}],"answer":"b","category":"Divers & Approfondissement","explanation":"1988, A300 abattu par l'USS Vincennes."},
    {"id":282,"question":"Detournement AF8969 : quel aéroport pour l'intervention ?","options":[{"id":"a","text":"Alger"},{"id":"b","text":"CDG"},{"id":"c","text":"Marseille-Marignane"},{"id":"d","text":"Orly"}],"answer":"c","category":"Divers & Approfondissement","explanation":"GIA prend l'avion à Alger. Intervention GIGN à Marseille-Marignane."},
    {"id":283,"question":"MH370 disparition : quel océan ?","options":[{"id":"a","text":"Atlantique"},{"id":"b","text":"Pacifique"},{"id":"c","text":"Indien"},{"id":"d","text":"Arctique"}],"answer":"c","category":"Divers & Approfondissement","explanation":"B777, disparu au-dessus de l'océan Indien, 239 à bord, jamais retrouvé."},
    {"id":284,"question":"Germanwings 9525 : cause ?","options":[{"id":"a","text":"Panne moteur"},{"id":"b","text":"Météo"},{"id":"c","text":"Crash volontaire du copilote"},{"id":"d","text":"Collision en vol"}],"answer":"c","category":"Divers & Approfondissement","explanation":"A320, crash volontaire dans les Alpes françaises en 2015, 150 morts."},
    {"id":285,"question":"B737 MAX cloué au sol pendant ?","options":[{"id":"a","text":"6 mois"},{"id":"b","text":"12 mois"},{"id":"c","text":"20 mois"},{"id":"d","text":"36 mois"}],"answer":"c","category":"Divers & Approfondissement","explanation":"Cloué au sol 20 mois suite aux 2 crashes (346 morts, système MCAS défaillant)."},
    {"id":286,"question":"IATA créée en ?","options":[{"id":"a","text":"1919"},{"id":"b","text":"1944"},{"id":"c","text":"1945"},{"id":"d","text":"1958"}],"answer":"c","category":"Divers & Approfondissement","explanation":"IATA = International Air Transport Association, 1945."},
    {"id":287,"question":"FAA = autorité aviation de ?","options":[{"id":"a","text":"France"},{"id":"b","text":"Europe"},{"id":"c","text":"USA"},{"id":"d","text":"Canada"}],"answer":"c","category":"Divers & Approfondissement","explanation":"FAA = Federal Aviation Administration (USA), 1958."},
    {"id":288,"question":"NTSB enquête sur les accidents de ?","options":[{"id":"a","text":"France"},{"id":"b","text":"Europe"},{"id":"c","text":"USA"},{"id":"d","text":"Monde entier"}],"answer":"c","category":"Divers & Approfondissement","explanation":"NTSB = National Transportation Safety Board (USA), 1967."},
    {"id":289,"question":"LAPL permet de piloter ?","options":[{"id":"a","text":"Avions de ligne"},{"id":"b","text":"Avions légers avec restrictions"},{"id":"c","text":"Hélicoptères uniquement"},{"id":"d","text":"ULM uniquement"}],"answer":"b","category":"Divers & Approfondissement","explanation":"LAPL = Light Aircraft Pilot Licence, avions légers, restrictions passagers."},
    {"id":290,"question":"MPL = licence pour ?","options":[{"id":"a","text":"Commandant de bord"},{"id":"b","text":"Copilote en équipage multi-pilotes"},{"id":"c","text":"Vol privé"},{"id":"d","text":"Instructeur"}],"answer":"b","category":"Divers & Approfondissement","explanation":"MPL = Multi-crew Pilot Licence. Formation intégrée Cadets AF."},

    # --- ALLIANCES & GÉOGRAPHIE ---
    {"id":291,"question":"Siège de SkyTeam ?","options":[{"id":"a","text":"Paris"},{"id":"b","text":"Amsterdam"},{"id":"c","text":"Atlanta"},{"id":"d","text":"Séoul"}],"answer":"b","category":"Divers & Approfondissement","explanation":"Siège SkyTeam : Amsterdam."},
    {"id":292,"question":"ITA Airways a rejoint quelle alliance ?","options":[{"id":"a","text":"SkyTeam"},{"id":"b","text":"Star Alliance"},{"id":"c","text":"Oneworld"},{"id":"d","text":"Aucune"}],"answer":"b","category":"Divers & Approfondissement","explanation":"ITA Airways a quitté SkyTeam (fév. 2025) pour Star Alliance (rachat Lufthansa)."},
    {"id":293,"question":"Aeroflot suspendue de SkyTeam depuis ?","options":[{"id":"a","text":"2014"},{"id":"b","text":"2020"},{"id":"c","text":"2022"},{"id":"d","text":"2024"}],"answer":"c","category":"Divers & Approfondissement","explanation":"Suspendue depuis 2022 (guerre en Ukraine)."},
    {"id":294,"question":"Ouagadougou est la capitale de ?","options":[{"id":"a","text":"Mali"},{"id":"b","text":"Burkina Faso"},{"id":"c","text":"Niger"},{"id":"d","text":"Sénégal"}],"answer":"b","category":"Divers & Approfondissement","explanation":"Ouagadougou = capitale du Burkina Faso (fréquemment demandé au PSY0)."},
    {"id":295,"question":"Abidjan est en ?","options":[{"id":"a","text":"Sénégal"},{"id":"b","text":"Ghana"},{"id":"c","text":"Côte d'Ivoire"},{"id":"d","text":"Cameroun"}],"answer":"c","category":"Divers & Approfondissement","explanation":"Abidjan, principale ville et centre économique de Côte d'Ivoire."},
    {"id":296,"question":"Bogota est la capitale de ?","options":[{"id":"a","text":"Venezuela"},{"id":"b","text":"Colombie"},{"id":"c","text":"Pérou"},{"id":"d","text":"Équateur"}],"answer":"b","category":"Divers & Approfondissement","explanation":"Bogota = capitale de la Colombie."},
    {"id":297,"question":"Paris-SF : la route orthodromique passe par ?","options":[{"id":"a","text":"Portugal et Açores"},{"id":"b","text":"Islande et Groenland"},{"id":"c","text":"Canaries et Bermudes"},{"id":"d","text":"Ligne droite sur la carte"}],"answer":"b","category":"Divers & Approfondissement","explanation":"Route orthodromique Paris-SF passe par l'Islande et le Groenland (grand cercle)."},
    {"id":298,"question":"Nombre d'ONG partenaires Flying Blue ?","options":[{"id":"a","text":"5"},{"id":"b","text":"10"},{"id":"c","text":"18"},{"id":"d","text":"25"}],"answer":"c","category":"Divers & Approfondissement","explanation":"Dons de Miles à 18 ONG (WWF, Croix-Rouge…)."},
    {"id":299,"question":"Objectif net zéro émissions d'AF ?","options":[{"id":"a","text":"2030"},{"id":"b","text":"2040"},{"id":"c","text":"2050"},{"id":"d","text":"2060"}],"answer":"c","category":"ETOPS, CRM & Systèmes","explanation":"Objectif 2050 : Net zéro émissions. 2030 : -30% CO₂ par pax-km vs 2019."},
    {"id":300,"question":"Investissement flotte AF par an ?","options":[{"id":"a","text":">500 M€"},{"id":"b","text":">1 Md€"},{"id":"c","text":">2 Md€"},{"id":"d","text":">5 Md€"}],"answer":"b","category":"ETOPS, CRM & Systèmes","explanation":">1 Md€/an d'investissement flotte."},

    # --- BONUS ---
    {"id":301,"question":"Dernier vol du Concorde ?","options":[{"id":"a","text":"25 juillet 2000"},{"id":"b","text":"11 septembre 2003"},{"id":"c","text":"26 novembre 2003"},{"id":"d","text":"1er janvier 2004"}],"answer":"c","category":"Histoire","explanation":"Dernier vol : 26 novembre 2003."},
    {"id":302,"question":"50e A220-300 livré à AF en ?","options":[{"id":"a","text":"2022"},{"id":"b","text":"2023"},{"id":"c","text":"2024"},{"id":"d","text":"2025"}],"answer":"c","category":"Air France & Flotte","explanation":"2024. Objectif : 60 A220."},
    {"id":303,"question":"Récompense AF 2022 ?","options":[{"id":"a","text":"Best Airline World"},{"id":"b","text":"World's Leading Airline to Europe"},{"id":"c","text":"Most Punctual Airline"},{"id":"d","text":"Best Crew Service"}],"answer":"b","category":"Air France & Flotte","explanation":"« World's Leading Airline to Europe 2022 », 4★ APEX."},
    {"id":304,"question":"An-225 Mriya détruit en ?","options":[{"id":"a","text":"2014"},{"id":"b","text":"2019"},{"id":"c","text":"2022"},{"id":"d","text":"2024"}],"answer":"c","category":"Divers & Approfondissement","explanation":"Détruit en Ukraine en 2022. Plus lourd avion jamais construit (640t MTOW)."},
    {"id":305,"question":"Beluga XL transporte ?","options":[{"id":"a","text":"Des passagers VIP"},{"id":"b","text":"Des pièces d'avions Airbus"},{"id":"c","text":"Du fret militaire"},{"id":"d","text":"Du carburant"}],"answer":"b","category":"Divers & Approfondissement","explanation":"Plus grande soute au monde, transporte les pièces d'avions Airbus entre les usines."},
    {"id":306,"question":"Réserve finale obligatoire (jet) ?","options":[{"id":"a","text":"15 min"},{"id":"b","text":"30 min"},{"id":"c","text":"45 min"},{"id":"d","text":"60 min"}],"answer":"b","category":"ETOPS, CRM & Systèmes","explanation":"30 min de vol minimum en réserve pour les avions à réaction."},
    {"id":307,"question":"Aquaplaning : risque sur piste ?","options":[{"id":"a","text":"Sèche"},{"id":"b","text":"Mouillée"},{"id":"c","text":"Enneigée"},{"id":"d","text":"Verglacée"}],"answer":"b","category":"ETOPS, CRM & Systèmes","explanation":"Piste mouillée = ↑ distance de freinage + risque d'aquaplaning."},
    {"id":308,"question":"Carburant embarqué inclut ?","options":[{"id":"a","text":"Trip fuel seulement"},{"id":"b","text":"Trip + réserves + déroutement + attente + taxi"},{"id":"c","text":"Trip + taxi"},{"id":"d","text":"Tout le kérosène disponible"}],"answer":"b","category":"ETOPS, CRM & Systèmes","explanation":"Trip fuel + réserves + déroutement + attente + taxi."},
    {"id":309,"question":"Ligne de roulage (taxiway) est de couleur ?","options":[{"id":"a","text":"Blanche"},{"id":"b","text":"Jaune"},{"id":"c","text":"Verte"},{"id":"d","text":"Rouge"}],"answer":"b","category":"ETOPS, CRM & Systèmes","explanation":"Axe central de roulage = ligne jaune."},
    {"id":310,"question":"ROGER signifie ?","options":[{"id":"a","text":"Oui"},{"id":"b","text":"Non"},{"id":"c","text":"J'ai bien reçu votre message"},{"id":"d","text":"Je vais exécuter"}],"answer":"c","category":"ETOPS, CRM & Systèmes","explanation":"ROGER = j'ai bien reçu. WILCO = je vais exécuter. AFFIRM = oui."},
    {"id":311,"question":"Ne jamais dire 'repeat', on dit ?","options":[{"id":"a","text":"ROGER"},{"id":"b","text":"WILCO"},{"id":"c","text":"SAY AGAIN"},{"id":"d","text":"CONFIRM"}],"answer":"c","category":"ETOPS, CRM & Systèmes","explanation":"« Repeat » est réservé à l'artillerie. En aviation : SAY AGAIN."},
    {"id":312,"question":"Altitude-densité tient compte de ?","options":[{"id":"a","text":"La vraie densité de l'air"},{"id":"b","text":"L'altitude GPS"},{"id":"c","text":"Le poids de l'avion"},{"id":"d","text":"La vitesse du vent"}],"answer":"a","category":"ETOPS, CRM & Systèmes","explanation":"Altitude fictive tenant compte de la vraie densité de l'air (température + altitude terrain)."},
    {"id":313,"question":"Vent de face au décollage = ?","options":[{"id":"a","text":"Distance de roulement augmentée"},{"id":"b","text":"Distance de roulement diminuée"},{"id":"c","text":"Aucun effet"},{"id":"d","text":"Avion plus lourd"}],"answer":"b","category":"ETOPS, CRM & Systèmes","explanation":"Vent de face = favorable : ↓ distance de roulement au décollage et à l'atterrissage."},
    {"id":314,"question":"IRS dérive de combien par heure ?","options":[{"id":"a","text":"~0.1 NM/h"},{"id":"b","text":"~1 NM/h"},{"id":"c","text":"~10 NM/h"},{"id":"d","text":"~100 NM/h"}],"answer":"b","category":"Navigation & Météo","explanation":"IRS/INS : dérive ~1 NM/h. Autonome, aucune émission. Recalé par VOR/DME quand disponible."},
    {"id":315,"question":"Pente du glide slope ILS ?","options":[{"id":"a","text":"2°"},{"id":"b","text":"3°"},{"id":"c","text":"5°"},{"id":"d","text":"7°"}],"answer":"b","category":"Navigation & Météo","explanation":"Pente standard du Glide Slope = 3°."},
    {"id":316,"question":"Bases AF en province (hors CDG/Orly) ?","options":[{"id":"a","text":"Lyon, Marseille, Toulouse, Bordeaux, Nice"},{"id":"b","text":"Lyon, Nantes, Lille"},{"id":"c","text":"Marseille, Strasbourg, Rennes"},{"id":"d","text":"Toulouse uniquement"}],"answer":"a","category":"Air France & Flotte","explanation":"Lyon (LYS), Marseille (MRS), Toulouse (TLS), Bordeaux (BOD), Nice (NCE)."},
    {"id":317,"question":"Nombre d'A350 commandés par AF (objectif) ?","options":[{"id":"a","text":"40"},{"id":"b","text":"60"},{"id":"c","text":"90+"},{"id":"d","text":"120"}],"answer":"c","category":"Air France & Flotte","explanation":"~40 en service, objectif 90+ avec commandes."},
    {"id":318,"question":"DC-3 est surnommé ?","options":[{"id":"a","text":"Le Jumbo"},{"id":"b","text":"L'avion qui a démocratisé le transport aérien"},{"id":"c","text":"Le Concorde des pauvres"},{"id":"d","text":"Le monstre des airs"}],"answer":"b","category":"Histoire","explanation":"Le DC-3 (années 1930-50) a démocratisé le transport aérien. Bimoteur à pistons."},
    {"id":319,"question":"Premier Salon Aéro au Grand Palais ?","options":[{"id":"a","text":"1903"},{"id":"b","text":"1909"},{"id":"c","text":"1920"},{"id":"d","text":"1936"}],"answer":"b","category":"Histoire","explanation":"1909, Grand Palais Paris. Aujourd'hui au Bourget (années impaires)."},
    {"id":320,"question":"Objectif nombre d'A220 chez AF ?","options":[{"id":"a","text":"40"},{"id":"b","text":"50"},{"id":"c","text":"60"},{"id":"d","text":"80"}],"answer":"c","category":"Air France & Flotte","explanation":"Objectif : 60 A220. 50e livré en 2024."},
]

existing_q.extend(new_q)
print(f"Total questions: {len(existing_q)}")

# Update mode hints in the output
out = f"// PSY0 Training Data - V3 - Auto-generated\n"
out += f"// {len(existing_q)} questions + {len(existing_fc)} flashcards\n\n"
out += "const qcmData = " + json.dumps(existing_q, indent=2, ensure_ascii=False) + ";\n\n"
out += "const flashcardData = " + json.dumps(existing_fc, indent=2, ensure_ascii=False) + ";\n"

with open("/Users/maximeleboeuf/Cadet AF/PSY0_Training/data/questions.js", 'w', encoding='utf-8') as f:
    f.write(out)

print(f"✅ Generated {len(existing_q)} questions and {len(existing_fc)} flashcards")
